#!/usr/bin/env zsh

# run bspwm configurations
. ~/.config/bspwm/utilities.sh && configure_bspwm
. ~/.config/bspwm/utilities.sh && configure_workspaces
. ~/.config/bspwm/utilities.sh && configure_keyboard
. ~/.config/bspwm/utilities.sh && subscribe_focused

# run display configurtation
. ~/.config/display/utilities.sh && configure_display true

# run autostart
. ~/.config/bspwm/utilities.sh && autostart