#!/usr/bin/env zsh

# xresources
xrdb -merge "$HOME/.Xresources"

# dbus environment
DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
export DBUS_SESSION_BUS_ADDRESS
dbus-update-activation-environment --verbose --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY 
# dbus environment
# systemctl --user import-environment DISPLAY XAUTHORITY
# dbus-update-activation-environment DISPLAY XAUTHORITY

# java desktop workaround 
export _JAVA_AWT_WM_NONREPARENTING=1

# default cursor
xsetroot -cursor_name left_ptr

# start bspwm
# exec dbus-launch --exit-with-session bspwm
exec bspwm
