#!/bin/sh

# xresources
xrdb -merge "$HOME/.Xresources"

# dbus environment
systemctl --user import-environment DISPLAY XAUTHORITY
dbus-update-activation-environment DISPLAY XAUTHORITY

# java desktop workaround 
xprop -root -remove _NET_WM_NAME
xprop -root -f _NET_WM_NAME 8s -set _NET_WM_NAME "LG3D"

# default cursor
xsetroot -cursor_name left_ptr

# start bspwm
exec bspwm
