#!/usr/bin/env bash

# xauthority
systemctl --user import-environment DISPLAY XAUTHORITY
dbus-update-activation-environment DISPLAY XAUTHORITY

# java desktop workaround 
xprop -root -remove _NET_WM_NAME
xprop -root -f _NET_WM_NAME 8s -set _NET_WM_NAME "LG3D"


# load xresources
xrdb -merge "$HOME/.Xresources"

# load profile
# . ~/.profile

xsetroot -cursor_name left_ptr

# start bspwm
exec dbus-launch bspwm


# userresources=$HOME/.Xresources
# usermodmap=$HOME/.Xmodmap
# sysresources=/etc/X11/xinit/.Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap

# # merge in defaults and keymaps

# if [ -f $sysresources ]; then
#     xrdb -merge $sysresources

# fi

# if [ -f $sysmodmap ]; then
#     xmodmap $sysmodmap
# fi

# if [ -f "$userresources" ]; then
#     xrdb -merge "$userresources"

# fi

# if [ -f "$usermodmap" ]; then
#     xmodmap "$usermodmap"
# fi

# # start some nice programs
# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

# xrandr --auto
# xsetroot -cursor_name left_ptr

# exec dbus-launch bspwm
